### ISSUE TITLE
API_KEY hardcoded

### ISSUE THREAD

**Issue by diegoparrilla** [clfolmar/react-ipverifier#1]
Your code (app.js) has the Apility.io API_KEY hardcoded. A terrible coding practice, specially if you want to show your coding skills to a potential job opportunity.

**Comment by clfolmar** [comment]
Diego thanks for the tip! I thoroughly agree, and this is actually the rough draft of what I'll be submitting... I'll actually be taking things like this, along with a few other things that should be taking advantage of environment variables into account going into the finalized solution.
